# 🔹 build stage
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app
COPY app .
RUN mvn clean package -DskipTests

# 🔹 runtime stage
FROM eclipse-temurin:21-jdk

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
