package GraficoCategoria;

public enum Categoria {
    RELACOES_INTERNACIONAIS(),
    LIBERDADE_DEMOCRACIA(),
    SISTEMA_POLITICO(),
    ECONOMIA(),
    BEM_ESTAR_QUALIDADE_DE_VIDA(),
    ESTRUTURA_DA_SOCIEDADE(),
    GRUPOS_SOCIAIS();
}
