FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar

EXPOSE 8080
EXPOSE 5005

CMD ["java", "-jar", "/app/app.jar"]
