
name: CI-CD

on:
  pull_request:
  push:
    branches: [ "main" ]
  merge_group:
    types: checks_requested
    

  workflow_dispatch:
  

jobs:

  #1. Detecta Mudança em Determinados Diretórios
  detect-changes:
    runs-on: ubuntu-latest
    
    outputs:
      java: ${{ steps.filter.outputs.java }}
      python: ${{ steps.filter.outputs.python }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            java:
              - 'backend/sistema-java/app/**'
            python:
              - 'backend/ai-python/**'



  #2. CI JAVA COM BUILD E TEST
  java:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.java == 'true'

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: eleicoes_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
          
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build + Test Java
        working-directory: 'backend/sistema-java/app/'
        run: mvn clean install
        env:
          DB_USER_POSTGRES: postgres
          DB_URL: jdbc:postgresql://localhost:5432/eleicoes_db
          DB_PASSWORD_POSTGRES: postgres


  #3. CI PYTHON COM BUILD E TEST
  python:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.python == 'true'
    env:
      APP_ENV:
      GOOGLE_API_KEY: ${{secrets.IA_SERVICE_GOOGLE_API_KEY_1}}
      AWS_ACCESS_KEY_ID: ${{secrets.IA_SERVICE_AWS_AK}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.IA_SERVICE_SK}}
      AWS_DEFAULT_REGION: ${{secrets.IA_SERVICE_AWS_REGION}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências
        working-directory: 'backend/ai-python/'
        run: pip install -r requirements.txt

      - name: Rodar testes
        working-directory: 'backend/ai-python/'
        run: pytest



  #4. PREPARAR VERSÃO DA IMAGEM DOCKER
  prepare:
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'

    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

          

  #5. BUILD IMAGEM DE JAVA E PUBLICAR NO DOCKER HUB
  build-java-image:
    runs-on: ubuntu-latest
    needs: [prepare, detect-changes, java]
    if: needs.detect-changes.outputs.java == 'true' && github.event_name == 'merge_group'

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{secrets.DOCKER_HUB_USER}}
        password: ${{secrets.DOCKER_HUB_TOKEN}}
        
    - name: Build da Imagem Java
      run: |
        docker build \
            -t ${{ secrets.DOCKER_HUB_USER }}/system-eleic:${{ needs.prepare.outputs.tag }} \
            -t ${{ secrets.DOCKER_HUB_USER }}/system-eleic:latest \
            ./backend/sistema-java/app
            
    - name: Push Imagem Java
      run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/system-eleic:${{ needs.prepare.outputs.tag }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/system-eleic:latest



  #6. BUILD IMAGEM DE PYTHON E PUBLICAR NO DOCKER HUB
  build-python-image:
    runs-on: ubuntu-latest
    needs: [prepare, detect-changes, python]
    if: needs.detect-changes.outputs.python == 'true' && github.event_name == 'merge_group'

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{secrets.DOCKER_HUB_USER_PYTHON}}
        password: ${{secrets.DOCKER_HUB_TOKEN_PYTHON}}
    
    - name: Build da Imagem Python
      run: |
        docker build \
              -t ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:${{ needs.prepare.outputs.tag }} \
              -t ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:latest \
              "./backend/ai-python"
            
    - name: Push Imagem Python
      run: |
          docker push ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:${{ needs.prepare.outputs.tag }}
          docker push ${{ secrets.DOCKER_HUB_USER_PYTHON }}/ai-sys-eleic:latest

  
