
name: CI 

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  workflow_dispatch:


  

jobs:

  detect-changes:
      runs-on: ubuntu-latest
      outputs:
        java_changed: ${{ steps.check.outputs.java_changed }}
        python_changed: ${{ steps.check.outputs.python_changed }}
  
      steps:
        - name: Checkout code with full history
          uses: actions/checkout@v3
          with:
            fetch-depth: 0   # importantíssimo para ver todos os commits e PRs
  
        - name: Check directories
          id: check
          run: |
            # Escapando caracteres especiais no grep
            JAVA_DIR='Sistema (JAVA)/app/'
            PYTHON_DIR='AI (Python)/app/'
  
            # Verifica se houve mudança no diretório Java
            if git diff --name-only origin/main...HEAD | grep -F -q "$JAVA_DIR"; then
              echo "java_changed=true" >> $GITHUB_OUTPUT
            else
              echo "java_changed=false" >> $GITHUB_OUTPUT
            fi
  
            # Verifica se houve mudança no diretório Python
            if git diff --name-only origin/main...HEAD | grep -F -q "$PYTHON_DIR"; then
              echo "python_changed=true" >> $GITHUB_OUTPUT
            else
              echo "python_changed=false" >> $GITHUB_OUTPUT
            fi
  
        - name: Output results
          run: |
            echo "Java directory changed? ${{ steps.check.outputs.java_changed }}"
            echo "Python directory changed? ${{ steps.check.outputs.python_changed }}"


  java:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.java_changed == 'true'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build + Test Java
        working-directory: 'Sistema (JAVA)/app/'
        run: mvn clean install

  python:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.python_changed == 'true'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        working-directory: 'AI (Python)/app/'
        run: pip install -r requirements.txt

      - name: Rodar testes
        working-directory: 'AI (Python)/app/**'
        run: pytest
